min_particles: 650
max_particles: 4000
transform_tolerance: 0.8

kld_err: 0.3
kld_z: 0.96

laser_min_range: 0.5
laser_max_range: 5
laser_max_beams: 73

laser_sigma_hit: 1.4

initialpose: [0.0, 0.0, 0.0]


odom_alpha1: 0.3
odom_alpha2: 0.5
odom_alpha3: 0.3
odom_alpha4: 0.3
odom_alpha5: 0.3

footprint: [[0.2, 0.0], [0.0,0.2], [0.0, -0.2]]