map_type: costmap

obstacle_range: 2.0
raytrace_range: 3.0

inflation_radius: 0.5
observation_sources: laser_scan_sensor


laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}


xy_goal_tolerance: 0.1
yaw_goal_tolerance: 0.1