map_type: costmap

obstacle_range: 1.5
raytrace_range: 1.5

transform_tolerance: 0.05

robot_radius: 0.2
inflation_radius: 0.055

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
