global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 1.0
   publish_frequency: 1.0
   width: 50.0
   height: 50.0
   resolution: 0.05
   static_map: true
   rolling_window: false


   laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: scan, marking: true, clearing: true}