global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 1.0
   publish_frequency: .5
   width: 50.0
   height: 50.0
   resolution: 0.5
   static_map: true
   rolling_window: false


