local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint 
   update_frequency: 2.0
   publish_frequency: 1.0
   width: 2.0
   height: 2.0
   resolution: 0.05
   static_map: false
   rolling_window: true


   laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: scan, marking: true, clearing: true}