local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint 
   update_frequency: 3.0
   publish_frequency: 1.0
   width: 30.0
   height: 30.0
   resolution: 0.01
   static_map: false
   rolling_window: true
   meter_scoring: true
   transform_tolerance: 1.5
